# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Api Files CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.x
      - run: npm install
      - run: echo "Salut!" && echo "PORT=${{vars.PORT}}" >> .env && echo "SIZE_DOWNLOAD_LIMIT=${{vars.SIZE_DOWNLOAD_LIMIT}}" >> .env && echo "ACCESS_TOKEN=${{vars.ACCESS_TOKEN}}" >> .env && echo "DIR_RECORDS=${{vars.DIR_RECORDS}}" >> .env
      - run: npx drizzle-kit generate:sqlite --schema=db.ts
      - run: npm run build --if-present
      # - run: pm2 start dist/index.js -f --name managerFileAsterisk:3012
      - run: pm2 restart managerFileAsterisk:3012
      # - run: pm2 save
