# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Api Files CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
        env:
          PORT: ${{ env.PORT }}
          SIZE_DOWNLOAD_LIMIT: ${{ env.SIZE_DOWNLOAD_LIMIT }}
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          DIR_RECORDS: ${{ env.DIR_RECORDS }}
      - run: npx drizzle-kit generate:sqlite --schema=db.ts
      - run: npm run build --if-present
      - run: pm2 start dist/index.js -f --name managerFileAsterisk:3012
      - run: pm2 restart managerFileAsterisk:3012
      - run: pm2 save
